version: "3.9"

services:
  financial-tracker-backend:
    image: lifemetrics360-financialtracker-backend
    ports:
      - "8080:8080"
  
  financial-tracker-frontend:
    image: lifemetrics360-financialtracker-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  user-management-backend:
    image: lifemetrics360-usermanagement-backend
    ports:
      - "8081:8081"

networks:
  default:
    name: lifemetrics360-network